export const GET_POST_BY_ID = 'GET_POST_BY_ID';
export const GET_POST_BY_ID_SUCCESS = 'GET_POST_BY_ID_SUCCESS';
export const GET_POST_BY_ID_ERROR = 'GET_POST_BY_ID_ERROR';

export const GET_COMMENTS_BY_POST_ID = 'GET_COMMENTS_BY_POST_ID';
export const GET_COMMENTS_BY_POST_ID_SUCCESS = 'GET_COMMENTS_BY_POST_ID_SUCCESS';
export const GET_COMMENTS_BY_POST_ID_ERROR = 'GET_COMMENTS_BY_POST_ID_ERROR';